
// This statement provides NULL.
#include <stdlib.h>

#define LAUNCHED_TEST_PACKET_TYPE 1
#define LOGGED_TEST_PACKET_TYPE 2
#define HALTED_TEST_PACKET_TYPE 3
#define RESET_TEST_PACKET_TYPE 4
#define CREATE_FILE_TEST_PACKET_TYPE 5
#define START_TEST_PACKET_TYPE 6
#define QUIT_TEST_PACKET_TYPE 7
#define CREATE_ALLOC_TEST_PACKET_TYPE 8
#define DELETE_ALLOC_TEST_PACKET_TYPE 9
#define CREATED_ALLOC_TEST_PACKET_TYPE 10
#define DELETED_ALLOC_TEST_PACKET_TYPE 11


